### ISSUE TITLE
yy.tidialogs does not work with sdk 7.1.1?

### ISSUE THREAD

**Issue by chrystoffer** [dbankier/TiDialogs#22]
[ERROR] TiApplication: (KrollRuntimeThread) [13,760] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: Couldn’t load yy.tidialogs from loader dalvik.system.PathClassLoader[DexPathList[[zip file “/data/app/….apk”],nativeLibraryDirectories=[/data/app-lib/…, /system/lib]]]: findLibrary returned null; Titanium 7.1.1,2018/04/19 11:11,undefined

tiapp.xml
<module platform="android">yy.tidialogs</module>

js
var Dialogs = require("yy.tidialogs");

version 4.0.0 and sdk 7.1.1

**Comment by dbankier** [comment]
What version of tidialogs are you using?

**Comment by chrystoffer** [comment]
version 4.0.0
https://github.com/dbankier/TiDialogs/blob/master/dist/yy.tidialogs-android-4.0.0.zip

**Comment by matheusavi** [comment]
I have the same issue with sdk 7.4.1.GA

**Comment by chrystoffer** [comment]
Testing on **7.2.0.GA** is running normally.
